# Generated by Django 5.0.3 on 2024-03-23 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userincome', '0002_rename_income_userincome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userincome',
            old_name='sorce',
            new_name='source',
        ),
    ]
